In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/Crime_Data_from_2020_to_Present.csv')

In [3]:
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192100,200316304,08/26/2020 12:00:00 AM,08/25/2020 12:00:00 AM,2030,3,Southwest,319,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,2300 SCARFF ST,NaN,34.0316,-118.2808
192101,200617582,11/04/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1320,6,Hollywood,645,1,210,ROBBERY,...,IC,Invest Cont,210.0,NaN,NaN,NaN,SUNSET,ORANGE,34.0980,-118.3416
192102,201607814,04/06/2020 12:00:00 AM,04/06/2020 12:00:00 AM,1400,16,Foothill,1637,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,10500 MATHER AV,NaN,34.2597,-118.3096
192103,201807686,03/04/2020 12:00:00 AM,03/04/2020 12:00:00 AM,1000,18,Southeast,1842,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,AO,Adult Other,236.0,NaN,NaN,NaN,200 W 109TH ST,NaN,33.9374,-118.2762
192104,201206895,02/11/2020 12:00:00 AM,02/11/2020 12:00:00 AM,5,12,77th Street,1249,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,6400,NaN,NaN,NaN

In [4]:
df.head(15)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,34.0944,-118.3277
5,231808869,04/04/2023 12:00:00 AM,12/01/2020 12:00:00 AM,2300,18,Southeast,1826,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,9900 COMPTON AV,NaN,33.9467,-118.2463
6,230110144,04/04/2023 12:00:00 AM,07/03/2020 12:00:00 AM,900,1,Central,182,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1100 S GRAND AV,NaN,34.0415,-118.2620
7,220314085,07/22/2022 12:00:00 AM,05/12/2020 12:00:00 AM,1110,3,Southwest,303,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2500 S SYCAMORE AV,NaN,34.0335,-118.3537
8,231309864,04/28/2023 12:00:00 AM,12/09/2020 12:00:00 AM,1400,13,Newton,1375,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1300 E 57TH ST,NaN,33.9911,-118.2521
9,211904005,12/31/2020 12:00:00 AM,12/31/2020 12:00:00 AM,1220,19,Mission,1974,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,9000 CEDROS AV,NaN,34.2336,-118.4535
10,221804943,01/21/2022 12:00:00 AM,07/01/2020 12:00:00 AM,1335,18,Southeast,1822,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,100 W COLDEN AV,NaN,33.9492,-118.2739
11,221908151,04/12/2022 12:00:00 AM,10/01/2020 12:00:00 AM,1,19,Mission,1988,1,821,SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO...,...,IC,Invest Cont,812.0,821.0,NaN,NaN,13400 RANGOON ST,NaN,34.2285,-118.4258
12,230204214,01/05/2023 12:00:00 AM,02/01/2020 12:00:00 AM,800,2,Rampart,201,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,...,IC,Invest Cont,812.0,860.0,NaN,NaN,900 N MARIPOSA AV,NaN,34.0868,-118.2991
13,221008844,05/06/2022 12:00:00 AM,11/01/2020 12:00:00 AM,130,10,West Valley,1029,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,VALJEAN ST,VANOWEN AV,34.1939,-118.4859
14,230207571,03/16/2023 12:00:00 AM,01/01/2020 12:00:00 AM,1500,2,Rampart,271,2,810,"SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W...",...,JA,Juv Arrest,810.0,NaN,NaN,NaN,900 S LAKE ST,NaN,34.0539,-118.2799

In [5]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.921050e+05,192105.000000,192105.000000,192105.000000,192105.000000,192105.000000,192105.000000,192103.000000,70107.000000,192103.000000,15680.000000,547.000000,17.000000,192104.000000,192104.000000
mean,2.016208e+08,1351.751756,10.838031,1129.830176,1.419635,509.658067,30.046417,296.537300,364.937553,509.369104,952.128699,984.500914,983.588235,33.937853,-117.884711
std,3.005365e+06,649.235663,6.037134,603.826106,0.493501,209.876130,21.755373,212.608249,121.161452,209.649504,119.114221,47.531265,45.015357,2.146086,7.444907
min,8.170000e+02,1.000000,1.000000,101.000000,1.000000,110.000000,-3.000000,101.000000,101.000000,110.000000,210.000000,626.000000,821.000000,0.000000,-118.667600
25%,2.006095e+08,920.000000,6.000000,632.000000,1.000000,330.000000,11.000000,101.000000,311.000000,330.000000,998.000000,998.000000,998.000000,34.008575,-118.431200
50%,2.012062e+08,1430.000000,11.000000,1152.000000,1.000000,510.000000,31.000000,203.000000,400.000000,510.000000,998.000000,998.000000,998.000000,34.058000,-118.322400
75%,2.017062e+08,1900.000000,16.000000,1636.000000,2.000000,626.000000,46.000000,501.000000,400.000000,626.000000,998.000000,998.000000,998.000000,34.165400,-118.274400
max,2.421048e+08,2359.000000,21.000000,2198.000000,2.000000,956.000000,99.000000,974.000000,516.000000,956.000000,999.000000,999.000000,998.000000,34.329300,0.000000

In [6]:
df.shape

(192105, 28)

In [8]:
df.dtypes

DR_NO               int64
Date Rptd          object
DATE OCC           object
TIME OCC            int64
AREA                int64
AREA NAME          object
Rpt Dist No         int64
Part 1-2            int64
Crm Cd              int64
Crm Cd Desc        object
Mocodes            object
Vict Age            int64
Vict Sex           object
Vict Descent       object
Premis Cd         float64
Premis Desc        object
Weapon Used Cd    float64
Weapon Desc        object
Status             object
Status Desc        object
Crm Cd 1          float64
Crm Cd 2          float64
Crm Cd 3          float64
Crm Cd 4          float64
LOCATION           object
Cross Street       object
LAT               float64
LON               float64
dtype: object

In [16]:
missing_values=df.isnull().sum()
missing_values[missing_values>0]

Mocodes            25777
Vict Sex           24557
Vict Descent       24560
Premis Cd              2
Premis Desc           66
Weapon Used Cd    121998
Weapon Desc       121998
Crm Cd 1               2
Crm Cd 2          176425
Crm Cd 3          191558
Crm Cd 4          192088
Cross Street      158450
LAT                    1
LON                    1
dtype: int64

In [17]:
df.nunique()

DR_NO             192105
Date Rptd           1337
DATE OCC             377
TIME OCC            1434
AREA                  21
AREA NAME             21
Rpt Dist No         1153
Part 1-2               2
Crm Cd               129
Crm Cd Desc          129
Mocodes            79585
Vict Age             102
Vict Sex               4
Vict Descent          19
Premis Cd            298
Premis Desc          295
Weapon Used Cd        77
Weapon Desc           77
Status                 5
Status Desc            5
Crm Cd 1             131
Crm Cd 2              97
Crm Cd 3              20
Crm Cd 4               3
LOCATION           41514
Cross Street        5296
LAT                 5004
LON                 4761
dtype: int64

In [18]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')

In [24]:
df['AREA NAME'].unique()

array(['Wilshire', 'Central', 'Southwest', 'Van Nuys', 'Hollywood',
       'Southeast', 'Newton', 'Mission', 'Rampart', 'West Valley',
       'West LA', 'Olympic', 'Hollenbeck', 'Topanga', 'Northeast',
       '77th Street', 'Pacific', 'N Hollywood', 'Harbor', 'Foothill',
       'Devonshire'], dtype=object)

In [25]:
df['AREA NAME'].nunique()

21

In [26]:
df['Vict Age'].mean()

30.046417323859348

In [29]:
df['Vict Age'].median()

31.0

In [30]:
df['Vict Age'].std()

21.755372694613023

In [33]:
q1 = df['Vict Age'].quantile(0.25)
q3 = df['Vict Age'].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = df[(df['Vict Age'] < lower_bound) | (df['Vict Age'] > upper_bound)]['Vict Age']
print(outliers)

2588      99
2652      99
4472      99
17625     99
23242     99
          ..
181246    99
182723    99
184726    99
186148    99
189282    99
Name: Vict Age, Length: 81, dtype: int64

Q1 and Q3: These are the 25th and 75th percentiles, respectively.

IQR: This is the range between Q3 and Q1.
Bounds: Any value below the lower bound or above the upper bound is considered an outlier.

In [35]:
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

correlation_matrix = df[numerical_columns].corr()

print(correlation_matrix)

                   DR_NO  TIME OCC      AREA  Rpt Dist No  Part 1-2    Crm Cd  \
DR_NO           1.000000 -0.041059  0.212079     0.211874  0.079505 -0.031694
TIME OCC       -0.041059  1.000000  0.006731     0.006638 -0.031998  0.000352
AREA            0.212079  0.006731  1.000000     0.999022 -0.006168 -0.007174
Rpt Dist No     0.211874  0.006638  0.999022     1.000000 -0.006004 -0.006982
Part 1-2        0.079505 -0.031998 -0.006168    -0.006004  1.000000  0.733566
Crm Cd         -0.031694  0.000352 -0.007174    -0.006982  0.733566  1.000000
Vict Age        0.030716 -0.031996  0.007623     0.007498  0.178947 -0.009423
Premis Cd       0.099784 -0.059322 -0.000053    -0.000047  0.251436  0.122527
Weapon Used Cd  0.022002 -0.015342 -0.027155    -0.026639  0.425793  0.373192
Crm Cd 1       -0.031786  0.000511 -0.007372    -0.007172  0.734158  0.999201
Crm Cd 2       -0.111460  0.007574 -0.044370    -0.044731  0.102532  0.020651
Crm Cd 3       -0.021134 -0.061355  0.019470     0.019610  0.073442  0.078856
Crm Cd 4        0.076875  0.047858  0.079793     0.078701       NaN -0.091165
LAT             0.004326  0.006900  0.020374     0.020030 -0.037041 -0.050975
LON            -0.001522 -0.006761 -0.008688    -0.008461  0.037342  0.051111

                Vict Age  Premis Cd  Weapon Used Cd  Crm Cd 1  Crm Cd 2  \
DR_NO           0.030716   0.099784        0.022002 -0.031786 -0.111460
TIME OCC       -0.031996  -0.059322       -0.015342  0.000511  0.007574
AREA            0.007623  -0.000053       -0.027155 -0.007372 -0.044370
Rpt Dist No     0.007498  -0.000047       -0.026639 -0.007172 -0.044731
Part 1-2        0.178947   0.251436        0.425793  0.734158  0.102532
Crm Cd         -0.009423   0.122527        0.373192  0.999201  0.020651
Vict Age        1.000000   0.182907        0.075957 -0.009310 -0.024001
Premis Cd       0.182907   1.000000        0.206601  0.122389 -0.082732
Weapon Used Cd  0.075957   0.206601        1.000000  0.374068 -0.178905
Crm Cd 1       -0.009310   0.122389        0.374068  1.000000  0.039220
Crm Cd 2       -0.024001  -0.082732       -0.178905  0.039220  1.000000
Crm Cd 3        0.015272  -0.033199       -0.051867  0.123652  0.273215
Crm Cd 4        0.338526   0.235755       -0.212244 -0.166569 -0.108060
LAT             0.000538  -0.012219       -0.016787 -0.051116 -0.023638
LON             0.000458   0.012640        0.019187  0.051252  0.025209

                Crm Cd 3  Crm Cd 4       LAT       LON
DR_NO          -0.021134  0.076875  0.004326 -0.001522
TIME OCC       -0.061355  0.047858  0.006900 -0.006761
AREA            0.019470  0.079793  0.020374 -0.008688
Rpt Dist No     0.019610  0.078701  0.020030 -0.008461
Part 1-2        0.073442       NaN -0.037041  0.037342
Crm Cd          0.078856 -0.091165 -0.050975  0.051111
Vict Age        0.015272  0.338526  0.000538  0.000458
Premis Cd      -0.033199  0.235755 -0.012219  0.012640
Weapon Used Cd -0.051867 -0.212244 -0.016787  0.019187
Crm Cd 1        0.123652 -0.166569 -0.051116  0.051252
Crm Cd 2        0.273215 -0.108060 -0.023638  0.025209
Crm Cd 3        1.000000  0.454679 -0.012210 -0.051902
Crm Cd 4        0.454679  1.000000  0.103045 -0.376970
LAT            -0.012210  0.103045  1.000000 -0.998936
LON            -0.051902 -0.376970 -0.998936  1.000000

Part 1-2 and Weapon Used Cd: Part 1-2 also shows a moderate positive correlation with Weapon Used Cd. This suggests that incidents categorized under Part 1-2 (possibly serious crimes or incidents) are more likely to involve a recorded weapon used.

Victim Age and Crm Cd 4: Victim Age shows a noticeable positive correlation with Crm Cd 4. This could indicate that certain types of crimes (likely categorized under Crm Cd 4) tend to involve victims of a particular age group more frequently.

In [45]:
grouped_data = df.groupby('Part 1-2').agg({'TIME OCC': ['mean', 'sum'],'Vict Age': ['mean', 'sum'],
                                           'Weapon Used Cd': ['mean', 'sum'],'Rpt Dist No': ['mean', 'sum']})

In [46]:
grouped_data

             TIME OCC             Vict Age          Weapon Used Cd  \
                 mean        sum      mean      sum           mean
Part 1-2
1         1369.416437  152677608  26.73605  2980829     307.611425
2         1327.321098  107000663  34.62473  2791238     411.364080

                      Rpt Dist No
                 sum         mean        sum
Part 1-2
1          9650078.0  1132.913051  126309609
2         15934599.0  1125.566490   90736417

The analysis of the crime records dataset provides a comprehensive understanding of crime patterns, demographic influences, and correlations between various factors. This information is crucial for developing effective strategies to address crime, enhance public safety, and allocate resources efficiently.
There is a noticeable difference in the mean time of occurrence between incidents categorized under Part 1-2 as 1 and 2. This suggests potential patterns in the timing of different types of incidents.
Victim Age (Vict Age):

Incidents categorized under Part 1-2 as 2 have a higher mean victim age compared to those categorized as 1. This indicates a demographic difference in the age of victims involved in different types of incidents.

The higher mean value for 'Weapon Used Cd' in incidents categorized as 2 in Part 1-2 suggests a greater involvement or variety of weapons used in these incidents compared to those categorized as 1.

There is a minor difference in the mean reporting district number between incidents categorized under Part 1-2 as 1 and 2. This indicates some variability in the geographical distribution of incidents across these categories.